image:
  repository: rabbitmq
  tag: "3-management"
  pullPolicy: IfNotPresent

auth:
  username: ""
  password: ""

# Сервис: LoadBalancer для внешнего доступа к AMQP
service:
  type: LoadBalancer
  amqpPort: 5672
  managementPort: 15672

# Ingress для management UI (порт 15672)
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: rabbitmq.tataredu.test
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  size: 1Gi
  storageClass: standard
