{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tataredu.fullname" . }}-backend
  namespace: {{ .Values.namespace | default (include "tataredu.fullname" .) }}
  labels:
    {{- include "tataredu.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "tataredu.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "tataredu.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      initContainers:
        - name: wait-for-db
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          command: ['sh', '-c', 'until pg_isready -h postgres -p 5432; do echo waiting for database; sleep 2; done;']
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "tataredu.configMapName" . }}
            - secretRef:
                name: {{ include "tataredu.secretName" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tataredu.fullname" . }}-backend
  namespace: {{ .Values.namespace | default (include "tataredu.fullname" .) }}
  labels:
    {{- include "tataredu.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    {{- include "tataredu.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  type: {{ .Values.backend.service.type }}
{{- end }}


