---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tataredu.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tataredu.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "tataredu.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "tataredu.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      initContainers:
        {{- include "tataredu.initWaitPostgres" . | nindent 8 }}
        {{- include "tataredu.initWaitRabbitMQ" . | nindent 8 }}
        {{- include "tataredu.initWaitRedis" . | nindent 8 }}
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            {{- include "tataredu.backendEnvFrom" . | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tataredu.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tataredu.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    {{- include "tataredu.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
