---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tataredu.fullname" . }}-celery-beat
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tataredu.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-beat
spec:
  replicas: {{ .Values.celery.beat.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "tataredu.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery-beat
  template:
    metadata:
      labels:
        {{- include "tataredu.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery-beat
    spec:
      initContainers:
        {{- include "tataredu.initWaitRabbitMQ" . | nindent 8 }}
        {{- include "tataredu.initWaitRedis" . | nindent 8 }}
        {{- include "tataredu.initWaitPostgres" . | nindent 8 }}
      containers:
        - name: celery-beat
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          command:
            - celery
            - -A
            - tatarlang.celery
            - beat
            - --loglevel=info
          envFrom:
            {{- include "tataredu.backendEnvFrom" . | nindent 12 }}
          resources:
            {{- toYaml .Values.celery.beat.resources | nindent 12 }}
