apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tataredu.fullname" . }}-media
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tataredu.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.backend.media.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.backend.media.size }}
