{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: backend-migrate
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
{{- end }}


