apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tataredu.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tataredu.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER:     {{ .Values.postgres.user     | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  RABBITMQ_USER:     {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  RABBITMQ_PASS:     {{ .Values.rabbitmq.auth.password | b64enc | quote }}
  # CELERY_BROKER_URL строится из credentials + DNS-имени RabbitMQ сервиса
  CELERY_BROKER_URL: {{ include "tataredu.celeryBrokerUrl" . | b64enc | quote }}
  REDIS_PASSWORD:    {{ .Values.redis.auth.password | b64enc | quote }}
