image:
  repository: redis/redis-stack-server
  tag: "latest"
  pullPolicy: IfNotPresent

auth:
  password: ""

service:
  type: LoadBalancer

persistence:
  enabled: true
  size: 1Gi
  storageClass: manual
  hostPath: /data/tataredu/redis

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
