apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: tataredu
data:
  POSTGRES_DB: tatarlang
  POSTGRES_USER: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  RABBITMQ_USER: admin
  REACT_APP_API_URL: http://backend:8000/api/v1
  CELERY_BROKER_URL: amqp://admin:admin@rabbitmq:5672//
