apiVersion: batch/v1
kind: CronJob
metadata:
  name: backend-clearsessions
  namespace: tataredu
spec:
  schedule: "0 3 * * *" # каждый день в 03:00
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backend-clearsessions
              image: backend:latest
              imagePullPolicy: Never
              command: ["python", "manage.py", "clearsessions"]
              envFrom:
                - configMapRef:
                    name: app-config
                - secretRef:
                    name: app-secret

