apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  namespace: tataredu
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: backend-migrate
          image: backend:latest
          imagePullPolicy: Never
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret

