apiVersion: v1
kind: Secret
metadata:
  name: tataredu-secret
  namespace: tataredu
  labels:
    app.kubernetes.io/part-of: tataredu
type: Opaque

data:
  POSTGRES_USER: cG9zdGdyZXM=         # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=     # postgres
  RABBITMQ_USER: YWRtaW4=             # admin
  RABBITMQ_PASS: YWRtaW4=             # admin
  # amqp://admin:admin@rabbitmq:5672//
  CELERY_BROKER_URL: YW1xcDovL2FkbWluOmFkbWluQHJhYmJpdG1xOjU2NzIvLw==
