apiVersion: v1
kind: Secret
metadata:
  name: tataredu-tls
  namespace: tataredu
type: kubernetes.io/tls
data:
  # Заглушка: сюда нужно положить закодированные в base64 сертификат и ключ
  tls.crt: ZHVtbXktY2VydA==
  tls.key: ZHVtbXkta2V5

