deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  useTestSchema: true
  limits_config:
    retention_period: 6h
    reject_old_samples: true
    reject_old_samples_max_age: 24h

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 75m
      memory: 192Mi
    limits:
      cpu: 400m
      memory: 512Mi
  persistence:
    enabled: true
    size: 2Gi
    storageClass: standard

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

chunksCache:
  enabled: false
resultsCache:
  enabled: false
minio:
  enabled: false
lokiCanary:
  enabled: false
test:
  enabled: false

gateway:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 24Mi
    limits:
      cpu: 100m
      memory: 64Mi
