apiVersion: v2
name: vault
description: |
  HashiCorp Vault для TatarEdu — управление секретами.
  Использует официальный chart hashicorp/vault.
  Настроен: dev-режим, Ingress, web UI, AppRole auth.
type: application
version: 0.1.0
appVersion: "1.21.2"
dependencies:
  - name: vault
    version: "0.32.0"
    repository: "https://helm.releases.hashicorp.com"
    alias: vault
