
vault:
  global:
    enabled: true
  server:
    dev:
      enabled: true
      devRootToken: "root"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
        - host: vault.tataredu.test
          paths:
            - /
      tls:
        - secretName: vault-tls
          hosts:
            - vault.tataredu.test
  ui:
    enabled: true
    serviceType: ClusterIP
  injector:
    enabled: false
