{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tataredu.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tataredu.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "tataredu.fullname" . }}-backend
                port:
                  number: 8000
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: {{ include "tataredu.fullname" . }}-backend
                port:
                  number: 8000
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: {{ include "tataredu.fullname" . }}-backend
                port:
                  number: 8000
          - path: /redoc
            pathType: Prefix
            backend:
              service:
                name: {{ include "tataredu.fullname" . }}-backend
                port:
                  number: 8000
          - path: /media
            pathType: Prefix
            backend:
              service:
                name: {{ include "tataredu.fullname" . }}-backend
                port:
                  number: 8000
          {{- if .Values.flower.enabled }}
          - path: /flower
            pathType: Prefix
            backend:
              service:
                name: {{ include "tataredu.fullname" . }}-celery-flower
                port:
                  number: 5555
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tataredu.fullname" . }}-frontend
                port:
                  number: 3000
{{- end }}
