githubConfigUrl: https://github.com/BondarenkoMi/tatarlang
githubConfigSecret: arc-github-token

runnerScaleSetName: tataredu-runner
minRunners: 0
maxRunners: 1

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            cpu: 100m
            memory: 192Mi
          limits:
            cpu: 500m
            memory: 512Mi
