
postgres:
  user:     ref+vault://secret/tataredu/postgres?auth_method=approle#user
  password: ref+vault://secret/tataredu/postgres?auth_method=approle#password
  database: ref+vault://secret/tataredu/postgres?auth_method=approle#database


postgresql:
  auth:
    postgresPassword: ref+vault://secret/tataredu/postgres?auth_method=approle#password
    database:         ref+vault://secret/tataredu/postgres?auth_method=approle#database


rabbitmq:
  auth:
    username: ref+vault://secret/tataredu/rabbitmq?auth_method=approle#user
    password: ref+vault://secret/tataredu/rabbitmq?auth_method=approle#password
    erlangCookie: ref+vault://secret/tataredu/rabbitmq?auth_method=approle#erlang_cookie


redis:
  auth:
    password: ref+vault://secret/tataredu/redis?auth_method=approle#password

django:
  secretKey: ref+vault://secret/tataredu/django?auth_method=approle#secret_key
